[package]
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
categories = ["network-programming", "game-development", "wasm", "web-programming"]
description = "Bevy asset loader that transparently supports loading over http(s)"
edition = "2021"
keywords = ["gamedev", "networking", "wasm", "bevy"]
license = "MIT OR Apache-2.0"
name = "bevy_web_asset"
version = "0.3.0"

[dependencies]
bevy = {version = "0.8", default-features = false, features = ["bevy_asset"]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
surf = {version = "2.3", default-features = false, features = ["h1-client-rustls"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = {version = "0.3", default-features = false}
wasm-bindgen = {version = "0.2", default-features = false}
wasm-bindgen-futures = "0.4"
web-sys = {version = "0.3.22", default-features = false}
